import type { Node, Edge } from '../../stores/useGraphStore';

export interface BipartitePreset {
  id: string;
  name: string;
  directed: boolean;
  nodes: Node[];
  edges: Edge[];
  positions: Record<string, { x: number; y: number }>;
  expectedResult: boolean;
  note?: string;
}

export const bipartitePresets: BipartitePreset[] = [
  // UNDIRECTED BIPARTITE PRESETS (1-5)
  {
    id: 'simple-bipartite-4',
    name: 'Simple Bipartite (4 nodes)',
    directed: false,
    nodes: [
      { id: 'A', label: 'A' },
      { id: 'B', label: 'B' },
      { id: 'C', label: 'C' },
      { id: 'D', label: 'D' },
    ],
    edges: [
      { id: 'A-B', source: 'A', target: 'B' },
      { id: 'A-D', source: 'A', target: 'D' },
      { id: 'B-C', source: 'B', target: 'C' },
      { id: 'C-D', source: 'C', target: 'D' },
    ],
    positions: {
      A: { x: 400, y: 200 },
      B: { x: 600, y: 200 },
      C: { x: 600, y: 400 },
      D: { x: 400, y: 400 },
    },
    expectedResult: true,
  },
  {
    id: 'simple-bipartite-6',
    name: 'Bipartite — Two Sets (6 nodes)',
    directed: false,
    nodes: [
      { id: 'A', label: 'A' },
      { id: 'B', label: 'B' },
      { id: 'C', label: 'C' },
      { id: 'D', label: 'D' },
      { id: 'E', label: 'E' },
      { id: 'F', label: 'F' },
    ],
    edges: [
      { id: 'A-D', source: 'A', target: 'D' },
      { id: 'A-E', source: 'A', target: 'E' },
      { id: 'B-D', source: 'B', target: 'D' },
      { id: 'B-F', source: 'B', target: 'F' },
      { id: 'C-E', source: 'C', target: 'E' },
      { id: 'C-F', source: 'C', target: 'F' },
    ],
    positions: {
      A: { x: 300, y: 150 },
      B: { x: 300, y: 300 },
      C: { x: 300, y: 450 },
      D: { x: 650, y: 150 },
      E: { x: 650, y: 300 },
      F: { x: 650, y: 450 },
    },
    expectedResult: true,
  },
  {
    id: 'bipartite-path',
    name: 'Bipartite — Path Graph',
    directed: false,
    nodes: [
      { id: '1', label: '1' },
      { id: '2', label: '2' },
      { id: '3', label: '3' },
      { id: '4', label: '4' },
      { id: '5', label: '5' },
      { id: '6', label: '6' },
    ],
    edges: [
      { id: '1-2', source: '1', target: '2' },
      { id: '2-3', source: '2', target: '3' },
      { id: '3-4', source: '3', target: '4' },
      { id: '4-5', source: '4', target: '5' },
      { id: '5-6', source: '5', target: '6' },
    ],
    positions: {
      '1': { x: 150, y: 300 },
      '2': { x: 300, y: 300 },
      '3': { x: 450, y: 300 },
      '4': { x: 600, y: 300 },
      '5': { x: 750, y: 300 },
      '6': { x: 900, y: 300 },
    },
    expectedResult: true,
  },
  {
    id: 'bipartite-tree',
    name: 'Bipartite — Tree',
    directed: false,
    nodes: [
      { id: '1', label: '1' },
      { id: '2', label: '2' },
      { id: '3', label: '3' },
      { id: '4', label: '4' },
      { id: '5', label: '5' },
      { id: '6', label: '6' },
      { id: '7', label: '7' },
    ],
    edges: [
      { id: '1-2', source: '1', target: '2' },
      { id: '1-3', source: '1', target: '3' },
      { id: '2-4', source: '2', target: '4' },
      { id: '2-5', source: '2', target: '5' },
      { id: '3-6', source: '3', target: '6' },
      { id: '3-7', source: '3', target: '7' },
    ],
    positions: {
      '1': { x: 500, y: 100 },
      '2': { x: 300, y: 250 },
      '3': { x: 700, y: 250 },
      '4': { x: 200, y: 400 },
      '5': { x: 400, y: 400 },
      '6': { x: 600, y: 400 },
      '7': { x: 800, y: 400 },
    },
    expectedResult: true,
  },
  {
    id: 'bipartite-disconnected',
    name: 'Bipartite — Disconnected',
    directed: false,
    nodes: [
      { id: 'A', label: 'A' },
      { id: 'B', label: 'B' },
      { id: 'C', label: 'C' },
      { id: 'D', label: 'D' },
      { id: 'E', label: 'E' },
      { id: 'F', label: 'F' },
    ],
    edges: [
      { id: 'A-B', source: 'A', target: 'B' },
      { id: 'B-C', source: 'B', target: 'C' },
      { id: 'D-E', source: 'D', target: 'E' },
      { id: 'E-F', source: 'E', target: 'F' },
    ],
    positions: {
      A: { x: 200, y: 250 },
      B: { x: 350, y: 250 },
      C: { x: 500, y: 250 },
      D: { x: 600, y: 250 },
      E: { x: 750, y: 250 },
      F: { x: 900, y: 250 },
    },
    expectedResult: true,
  },

  // UNDIRECTED NON-BIPARTITE PRESETS (6-10)
  {
    id: 'odd-cycle-3',
    name: 'Not Bipartite — Triangle (3-cycle)',
    directed: false,
    nodes: [
      { id: 'A', label: 'A' },
      { id: 'B', label: 'B' },
      { id: 'C', label: 'C' },
    ],
    edges: [
      { id: 'A-B', source: 'A', target: 'B' },
      { id: 'B-C', source: 'B', target: 'C' },
      { id: 'C-A', source: 'C', target: 'A' },
    ],
    positions: {
      A: { x: 500, y: 150 },
      B: { x: 350, y: 400 },
      C: { x: 650, y: 400 },
    },
    expectedResult: false,
  },
  {
    id: 'odd-cycle-5',
    name: 'Not Bipartite — Pentagon (5-cycle)',
    directed: false,
    nodes: [
      { id: 'A', label: 'A' },
      { id: 'B', label: 'B' },
      { id: 'C', label: 'C' },
      { id: 'D', label: 'D' },
      { id: 'E', label: 'E' },
    ],
    edges: [
      { id: 'A-B', source: 'A', target: 'B' },
      { id: 'B-C', source: 'B', target: 'C' },
      { id: 'C-D', source: 'C', target: 'D' },
      { id: 'D-E', source: 'D', target: 'E' },
      { id: 'E-A', source: 'E', target: 'A' },
    ],
    positions: {
      A: { x: 500, y: 130 },
      B: { x: 720, y: 290 },
      C: { x: 640, y: 530 },
      D: { x: 360, y: 530 },
      E: { x: 280, y: 290 },
    },
    expectedResult: false,
  },
  {
    id: 'mixed-cycle',
    name: 'Not Bipartite — Mixed Graph',
    directed: false,
    nodes: [
      { id: 'A', label: 'A' },
      { id: 'B', label: 'B' },
      { id: 'C', label: 'C' },
      { id: 'D', label: 'D' },
      { id: 'E', label: 'E' },
      { id: 'F', label: 'F' },
    ],
    edges: [
      { id: 'A-B', source: 'A', target: 'B' },
      { id: 'B-C', source: 'B', target: 'C' },
      { id: 'C-A', source: 'C', target: 'A' },
      { id: 'C-D', source: 'C', target: 'D' },
      { id: 'D-E', source: 'D', target: 'E' },
      { id: 'E-F', source: 'E', target: 'F' },
    ],
    positions: {
      A: { x: 250, y: 200 },
      B: { x: 450, y: 150 },
      C: { x: 450, y: 350 },
      D: { x: 620, y: 250 },
      E: { x: 780, y: 200 },
      F: { x: 780, y: 400 },
    },
    expectedResult: false,
  },
  {
    id: 'not-bipartite-complex',
    name: 'Not Bipartite — Complex',
    directed: false,
    nodes: [
      { id: '1', label: '1' },
      { id: '2', label: '2' },
      { id: '3', label: '3' },
      { id: '4', label: '4' },
      { id: '5', label: '5' },
      { id: '6', label: '6' },
    ],
    edges: [
      { id: '1-2', source: '1', target: '2' },
      { id: '2-3', source: '2', target: '3' },
      { id: '3-4', source: '3', target: '4' },
      { id: '4-5', source: '4', target: '5' },
      { id: '5-1', source: '5', target: '1' },
      { id: '1-6', source: '1', target: '6' },
    ],
    positions: {
      '1': { x: 500, y: 300 },
      '2': { x: 650, y: 200 },
      '3': { x: 750, y: 350 },
      '4': { x: 650, y: 480 },
      '5': { x: 450, y: 430 },
      '6': { x: 350, y: 200 },
    },
    expectedResult: false,
  },
  {
    id: 'even-vs-odd',
    name: 'Even Cycle vs Odd Cycle',
    directed: false,
    nodes: [
      { id: 'A', label: 'A' },
      { id: 'B', label: 'B' },
      { id: 'C', label: 'C' },
      { id: 'D', label: 'D' },
      { id: 'E', label: 'E' },
      { id: 'F', label: 'F' },
      { id: 'G', label: 'G' },
      { id: 'H', label: 'H' },
    ],
    edges: [
      { id: 'A-B', source: 'A', target: 'B' },
      { id: 'B-C', source: 'B', target: 'C' },
      { id: 'C-D', source: 'C', target: 'D' },
      { id: 'D-A', source: 'D', target: 'A' },
      { id: 'E-F', source: 'E', target: 'F' },
      { id: 'F-G', source: 'F', target: 'G' },
      { id: 'G-E', source: 'G', target: 'E' },
    ],
    positions: {
      A: { x: 200, y: 200 },
      B: { x: 350, y: 200 },
      C: { x: 350, y: 350 },
      D: { x: 200, y: 350 },
      E: { x: 600, y: 180 },
      F: { x: 780, y: 300 },
      G: { x: 620, y: 420 },
      H: { x: 780, y: 180 },
    },
    expectedResult: false,
    note: 'Shows that one odd-cycle component makes the whole graph not bipartite',
  },

  // DIRECTED PRESETS (11-12)
  {
    id: 'directed-bipartite-4',
    name: 'Directed Bipartite (4 nodes)',
    directed: true,
    nodes: [
      { id: 'A', label: 'A' },
      { id: 'B', label: 'B' },
      { id: 'C', label: 'C' },
      { id: 'D', label: 'D' },
    ],
    edges: [
      { id: 'A-B', source: 'A', target: 'B' },
      { id: 'A-C', source: 'A', target: 'C' },
      { id: 'B-D', source: 'B', target: 'D' },
      { id: 'C-D', source: 'C', target: 'D' },
    ],
    positions: {
      A: { x: 400, y: 200 },
      B: { x: 600, y: 200 },
      C: { x: 400, y: 400 },
      D: { x: 600, y: 400 },
    },
    expectedResult: true,
  },
  {
    id: 'directed-non-bipartite-3',
    name: 'Directed Triangle (3 nodes)',
    directed: true,
    nodes: [
      { id: 'A', label: 'A' },
      { id: 'B', label: 'B' },
      { id: 'C', label: 'C' },
    ],
    edges: [
      { id: 'A-B', source: 'A', target: 'B' },
      { id: 'B-C', source: 'B', target: 'C' },
      { id: 'C-A', source: 'C', target: 'A' },
    ],
    positions: {
      A: { x: 500, y: 150 },
      B: { x: 350, y: 400 },
      C: { x: 650, y: 400 },
    },
    expectedResult: false,
  },
];
